
POST http://localhost:3000/register
Content-Type: application/json

{
   "name": "Gasaro",
   "email": "gasaro@example.com",
   "password": "123456"
}
###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RjYjAwMDgwOWJiMmQ4ZTUxYmRmNTIiLCJpYXQiOjE3NDI1MTcyNTMsImV4cCI6MTc0MjUyMDg1M30.eY1jBrJtCYhoj_vrYQPU0V3ZxUiKXsooH61i9hN60lM

###
POST http://localhost:3000/login
Content-Type: application/json

{
   "email": "gasaro@example.com",
   "password": "123456"
}
###
GET http://localhost:3000/getallexpenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RjYjAwMDgwOWJiMmQ4ZTUxYmRmNTIiLCJpYXQiOjE3NDI1MjQxNTUsImV4cCI6MTc0MjUyNzc1NX0.eAX6TDzFnI83loZ7eXwnq5Nu1XvOtDYrzHdIX4bETpw

###

POST http://localhost:3000/addexpense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RjYjAwMDgwOWJiMmQ4ZTUxYmRmNTIiLCJpYXQiOjE3NDI1MjQxNTUsImV4cCI6MTc0MjUyNzc1NX0.eAX6TDzFnI83loZ7eXwnq5Nu1XvOtDYrzHdIX4bETpw
Content-Type: application/json

{
   "amount": 50000,
   "reason": "bike"
}

###
DELETE  http://localhost:3000/deleteexpense/67dcd1dd02c6cc73bbe67aae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RjYjAwMDgwOWJiMmQ4ZTUxYmRmNTIiLCJpYXQiOjE3NDI1MjQxNTUsImV4cCI6MTc0MjUyNzc1NX0.eAX6TDzFnI83loZ7eXwnq5Nu1XvOtDYrzHdIX4bETpw

