
POST http://localhost:3000/register
Content-Type: application/json

{
   "name": "John noe",
   "email": "johnnoell11234@example.com",
   "password": "password123"
}
###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Q0OTA5ZmNlYWQzYjUzNGU3NTQ0ZjIiLCJpYXQiOjE3NDIzMTk5MjYsImV4cCI6MTc0MjMyNzEyNn0.VH-qndH_BO1YfhNlMeLgxKp5k6ztIp6DaXNSpv9lVnE

###
POST http://localhost:3000/login
Content-Type: application/json

{
   "email": "johndoe@example.com",
   "password": "password123"
}
###
GET http://localhost:3000/getallexpenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Q0OTA5ZmNlYWQzYjUzNGU3NTQ0ZjIiLCJpYXQiOjE3NDIzOTczMDYsImV4cCI6MTc0MjQwMDkwNn0.CuSbiKsibZW8JdMESwy5pSq6w-kG9y4H0saHh67xP_Q

###

POST http://localhost:3000/addexpense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2Q0OTA5ZmNlYWQzYjUzNGU3NTQ0ZjIiLCJpYXQiOjE3NDIzOTczMDYsImV4cCI6MTc0MjQwMDkwNn0.CuSbiKsibZW8JdMESwy5pSq6w-kG9y4H0saHh67xP_Q
Content-Type: application/json

{
   "amount": 50000,
   "reason": "bike"
}